name: unsplash
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_staggered_grid_view: ^0.4.0
  transparent_image: ^2.0.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  flutter_downloader: ^1.7.3
  permission_handler: ^9.2.0
  flutter_cache_manager: ^3.3.0
  provider: ^6.0.2
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/files/topics.json
    - assets/images/